### ISSUE TITLE
stepContainer does not grow with dynamic content

### ISSUE THREAD

**Issue by elroyshilling** [mstratman/jQuery-Smart-Wizard#15]
Hi there,

I have tested the wizard with Ajax content loading: the stepContainer does not grow with dynamic content???

Removed height:300px; still no luck.

Moving a step backward and returning to the previous step seems to autogrow the content but not inside current Container while loading dynamic ajax content?

![Screen Capture](https://f.cloud.github.com/assets/3511334/139396/6a1857ba-71f2-11e2-9e60-f11e4da62172.jpg)

**Comment by StateBarofArizona** [comment]
Having the same issue, tried your test button.  The step does resize but not large enough to fit all the content.  It seems to be short by 10 pixels.

**Comment by StateBarofArizona** [comment]
I was able to play with the values and get it to look good in IE and Firefox.  However, Chrome acts like it's just ignoring FixHeight.  It never reads the correct height of the elements in the div.

**Comment by G00sfraba** [comment]
Hello, I can see that this isn't fixed yet. I was able to reproduce it on my own site (currently in development).
The problem is as follows:
The wizard is setting the height of the stepContainer with the following line:
$this.elmStepContainer.height(_step($this, selStep).outerHeight());

Now this is ok if you have preloaded the content in the step before the initialization. The problem comes when you are changing the content with ajax requests. The ajax is ilways slower (because it is AJAX huh ) and the stepContainer is empty and/or with less content. The moment the AJAX response is received and we set the content based on the response the height of the step container is not recalculated.

Have in mind that I am changing the content by my own AJAX requests which are not connected with the SmartWizard.

So this is where the problem occures. Change the content of the smart wizard with AJAX with something bigger and it won't change the height of the wizard itslef.

I've commented out this line:
$this.elmStepContainer.height(_step($this, selStep).outerHeight());
Also set the animation to 'none'.

And now everything is fine with my wizards.

**Comment by wobblymusic** [comment]
The original version of this script is still being maintained. It includes an autoAdjustHeight parameter which, if you set to false, fixed all the height problems I was having. [More info](http://techlaboratory.net/smartwizard/documentation)
